# Authentication Database
auth.db.host=localhost
auth.db.port=3306
auth.db.name=university_auth
auth.db.username=root
auth.db.password=shashank

# ERP Database
erp.db.host=localhost
erp.db.port=3306
erp.db.name=university_erp
erp.db.username=root
erp.db.password=shashank
